# Add 'priority: middle 🔜' label to any file change
"priority: middle 🔜":
  - '**'
  - '.*'
  - '.*/**'
  
"section => add-ons":
  - addons/*

"section => administration":
  - administration/*

"section => configuration":
  - configuration/*

"section => development":
  - developers/*

"section => installation":
  - installation/*

"section => tutorials":
  - tutorials/*
